# Generated by Django 4.1.7 on 2023-03-20 15:11

import MyCurriculum.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('student_code', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True, validators=[MyCurriculum.models.user.student_code_valid])),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('permission_level', models.CharField(choices=[('student', 'Student'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='student', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
