# Generated by Django 4.1.7 on 2023-03-20 16:08

import MyCurriculum.models.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyCurriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[MyCurriculum.models.course.course_code_valid])),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
