# Generated by Django 4.1.7 on 2023-03-22 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyCurriculum', '0004_coursesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='MyCurriculum.course')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
